### PR TITLE
Updated checkAlgorithms.java to be compatible with JDK8

### PR DESCRIPTION
**Pull request by patrikcerbak**
As the title says. I replaced `List.of()` method with `Arrays.asList()`, which should be JDK8 compatible.

### CODE REVIEW

**Comment by judovana** [comment]
ty!

**Comment by judovana** [comment]
Interesting that original GH actions did not catch that. They run jdk8. Is th etes enabled to run as test inthis suite? It should

**Comment by patrikcerbak** [comment]
From the looks of it, it is not, it was not run in the GH actions. Isn't that because it basically is just a file? There is no jtreg header in it.

**Comment by judovana** [comment]
On longer run, it would be nice to have that header, at least for sake of GH in this project.

**Comment by patrikcerbak** [comment]
Ok, I definitely agree.

**Pull request merged**
